export enum BlockType {
  AIR = "AIR",
  DIRT = "DIRT",
  GRASS = "GRASS",
  STONE = "STONE",
  LEAVES = "LEAVES",
  WOOD = "WOOD",
  DEEPSLATE = "DEEPSLATE",
  COAL_ORE = "COAL_ORE",
  IRON_ORE = "IRON_ORE",
  DIAMOND_ORE = "DIAMOND_ORE",
}
